exclude: '^(venv|\.venv|__pycache__|\.mypy_cache|\.pytest_cache|\.git|build|dist)/'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: pretty-format-json
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
        args: [--max-line-length=131]
