name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: test code
        run: make test
    - name: run code
        run: make run
    - name: test all code
        run: make all
    - name: clean code
        run: make clean    
